<%@ Page Language="C#" AutoEventWireup="true" CodeFile="insert_into_empty_table.aspx.cs" Inherits="insert_into_empty_table" %>

<!DOCTYPE html>
<script runat="server">

    protected void Page_Load(object sender, EventArgs e)
    {

    }
</script>


<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 308px;
            height: 142px;
        }
    </style>
</head>
<body>
    <br />
    <font face="COOPER BLACK" size="6"> Table Name: Product_Table.......EmptyDataTemplate Concept</font>
    <br />

    <form id="form1" runat="server">
    <div>
    
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="id" DataSourceID="SqlDataSource1" ForeColor="Black" GridLines="Horizontal" Height="223px" ShowFooter="True" Width="593px" AutoGenerateDeleteButton="True" OnRowCommand="GridView1_RowCommand">
            <Columns>
                <asp:TemplateField>
                    <FooterTemplate>
                        <asp:Button ID="insert" runat="server" CommandName="insertaf" Text="Insert Item" OnClick="insert_Click" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Product_id" InsertVisible="False" SortExpression="id" >
                    <EditItemTemplate >
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("id") %>' ></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("id") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Product_Name" SortExpression="Product_Name">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Product_Name") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="namebox" runat="server"></asp:TextBox>
                    </FooterTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Product_Name") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Product_Type" SortExpression="Product_Type">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Product_Type") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="typebox" runat="server"></asp:TextBox>
                    </FooterTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("Product_Type") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Product_Price" SortExpression="Product_Price">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("Product_Price") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="pricebox" runat="server"></asp:TextBox>
                    </FooterTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("Product_Price") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Product_image" SortExpression="Product_image" >
                    <EditItemTemplate>
                        &nbsp;<br />
                    
                    </EditItemTemplate>
                    <FooterTemplate>
                        <asp:FileUpload ID="FileUpload2" runat="server" ToolTip="choose an image" />&nbsp;&nbsp;
                            <asp:Label ID="imgmsg1" runat="server" Text="Label"></asp:Label>
                    </FooterTemplate>
                    <ItemTemplate>
                        <asp:Image ID="Image1" runat="server" Height="101px" Width="128px" ImageUrl='<%# Eval("Product_image") %>' />
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            <EmptyDataTemplate>
                <table align="center" cellpadding="2" class="auto-style1">
                    <tr>
                        <td align="center">
                            <asp:Label ID="Label11" runat="server" Font-Bold="True" Font-Size="Medium" ForeColor="Black" Text="Product_id"></asp:Label>
                        </td>
                        <td align="center">
                            <asp:Label ID="Label7" runat="server" Font-Bold="True" Font-Size="Medium" ForeColor="Black" Text="Product_Name"></asp:Label>
                        </td>
                        <td align="center">
                            <asp:Label ID="Label8" runat="server" Font-Bold="True" Font-Size="Medium" ForeColor="Black" Text="Product_Type"></asp:Label>
                        </td>
                        <td align="center">
                            <asp:Label ID="Label9" runat="server" Font-Bold="True" Font-Size="Medium" ForeColor="Black" Text="Product_Price"></asp:Label>
                        </td>
                        <td align="center">
                            <asp:Label ID="Label10" runat="server" Font-Bold="True" Font-Size="Medium" ForeColor="Black" Text="Product_Image"></asp:Label>
                        </td>
                    </tr>
                    <tr>
                        <td align="center">
                            <asp:Label ID="Label12" runat="server" Text="Auto Incremented"></asp:Label>
                        </td>
                        <td align="center">
                            <asp:TextBox ID="namebox" runat="server"></asp:TextBox>
                        </td>
                        <td align="center">
                            <asp:TextBox ID="typebox" runat="server"></asp:TextBox>
                        </td>
                        <td align="center">
                            <asp:TextBox ID="pricebox" runat="server"></asp:TextBox>
                        </td>
                        <td align="center">
                            <asp:FileUpload ID="FileUpload2" runat="server" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5" align="center">
                            <asp:Button ID="insert2" runat="server" CommandName="insertbe" Text="Insert Item" OnClick="insert2_Click"  />
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <asp:Label ID="msg" runat="server" Text="Label"></asp:Label>
                        </td>
                    </tr>
                </table>
            </EmptyDataTemplate>
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" VerticalAlign="Middle" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#242121" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:aspdbConnectionString %>" DeleteCommand="DELETE FROM [Product_Table] WHERE [id] = @id" InsertCommand="INSERT INTO [Product_Table] ([Product_Name], [Product_Type], [Product_Price], [Product_image]) VALUES (@Product_Name, @Product_Type, @Product_Price, @Product_image)" SelectCommand="SELECT * FROM [Product_Table]" UpdateCommand="UPDATE [Product_Table] SET [Product_Name] = @Product_Name, [Product_Type] = @Product_Type, [Product_Price] = @Product_Price, [Product_image] = @Product_image WHERE [id] = @id">
            <DeleteParameters>
                <asp:Parameter Name="id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Product_Name" Type="String" />
                <asp:Parameter Name="Product_Type" Type="String" />
                <asp:Parameter Name="Product_Price" Type="Decimal" />
                <asp:Parameter Name="Product_image" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Product_Name" Type="String" />
                <asp:Parameter Name="Product_Type" Type="String" />
                <asp:Parameter Name="Product_Price" Type="Decimal" />
                <asp:Parameter Name="Product_image" Type="String" />
                <asp:Parameter Name="id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    
    </div>
    </form>
</body>
</html>
