<%@ Page Language="C#" AutoEventWireup="true"  CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        Working with XML file...<br />
        storing these field in a xml file as a db<br />
        <br />
    
    </div>
    <asp:Label ID="Label1" runat="server" 
        style="z-index: 1; left: 374px; top: 16px; position: absolute; width: 83px" 
        Text="Enter Name"></asp:Label>
    <asp:Label ID="Label2" runat="server" 
        style="z-index: 1; left: 375px; top: 61px; position: absolute" 
        Text="Enter Location"></asp:Label>
    <asp:Label ID="Label3" runat="server" 
        style="z-index: 1; left: 374px; top: 109px; position: absolute" 
        Text="Enter Email"></asp:Label>
    <asp:TextBox ID="TextBox1" runat="server" 
        style="z-index: 1; left: 471px; top: 16px; position: absolute"></asp:TextBox>
    <asp:TextBox ID="TextBox2" runat="server" 
        style="z-index: 1; left: 473px; top: 59px; position: absolute"></asp:TextBox>
    <asp:TextBox ID="TextBox3" runat="server" 
        style="z-index: 1; left: 474px; top: 105px; position: absolute"></asp:TextBox>
    <asp:Button ID="Button1" runat="server" onclick="Button1_Click" 
        style="z-index: 1; left: 481px; top: 179px; position: absolute" 
        Text="InsertData" />
    <asp:Label ID="Label4" runat="server" 
        style="z-index: 1; left: 374px; top: 149px; position: absolute; height: 26px" 
        Text="Enter Phone"></asp:Label>
    <asp:TextBox ID="TextBox4" runat="server" 
        style="z-index: 1; left: 472px; top: 146px; position: absolute"></asp:TextBox>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" onrowcancelingedit="GridView1_RowCancelingEdit" 
        onrowdeleting="GridView1_RowDeleting" 
        onrowupdating="GridView1_RowUpdating" 
        
        style="z-index: 1; left: 122px; top: 229px; position: absolute; height: 133px; width: 187px" OnRowEditing="GridView1_RowEditing" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
    </asp:GridView>
    </form>
</body>
</html>
