<%@ Page Language="C#" AutoEventWireup="true" CodeFile="gridview2.aspx.cs" Inherits="gridview2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <br />
   <center><font face="jokerman" size="6">Working with Table Having Primary key</font></center> 
    <br />
    <form id="form1" runat="server">
    <div>
    
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="True"  AutoGenerateDeleteButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" Height="261px" Width="548px" ShowFooter="True" style="margin-right: 0px" OnRowCommand="GridView1_RowCommand" >
            <Columns>
                <asp:TemplateField>
                    <FooterTemplate>
                        <asp:Button ID="insert" runat="server" Text="Insert" OnClick="insert_Click" CommandName="insertaf" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField>
                    <ItemTemplate>
                        <%# Eval ("id") %>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="idbox" runat="server"></asp:TextBox>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField>
                    <ItemTemplate>
                        <%# Eval ("Name") %>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="namebox" runat="server"></asp:TextBox>
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField>
                    <ItemTemplate>
                        <%# Eval ("Password") %>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="passwordbox" runat="server"></asp:TextBox>
                    </FooterTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:aspdbConnectionString %>" DeleteCommand="DELETE FROM [login] WHERE [id] = @id" InsertCommand="INSERT INTO [login] ([id], [Name], [Password]) VALUES (@id, @Name, @Password)" SelectCommand="SELECT * FROM [login]" UpdateCommand="UPDATE [login] SET [Name] = @Name, [Password] = @Password WHERE [id] = @id">
            <DeleteParameters>
                <asp:Parameter Name="id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="id" Type="Int32" />
                <asp:Parameter Name="Name" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Name" Type="String" />
                <asp:Parameter Name="Password" Type="String" />
                <asp:Parameter Name="id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    
    </div>
    </form>
</body>
</html>
