
<%@ Page Language="C#" AutoEventWireup="true" CodeFile="slider.aspx.cs" Inherits="slider" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">

	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, Content Slider, Flash Slideshow" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="Slider_Data/style.css" />
	<script type="text/javascript" src="Slider_Data/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->

</head>
<body style="background-color:#d7d7d7">
    <form id="form1" runat="server">
    <div>
    
        
<div id="wowslider-container1">
<div class="ws_images">
<ul>
<li><img src="Slider_images/1.jpg" alt="05" title="05" id="wows1_0"/></li>
<li><img src="Slider_images/2.jpg" alt="bara-imambara-lucknow" title="bara-imambara-lucknow" id="wows1_1"/></li>
<li><img src="Slider_images/3.jpg" alt="front" title="front" id="wows1_2"/></li>
<li><img src="Slider_images/4.jpg" alt="image1" title="image1" id="wows1_3"/></li>
<li><img src="Slider_images/5.jpg" alt="jama-masjid-lucknow" title="jama-masjid-lucknow" id="wows1_4"/></li>
<li><img src="Slider_images/6.jpg" alt="l1" title="l1" id="wows1_5"/></li>
<li><img src="Slider_images/7.jpg" alt="lko1" title="lko1" id="wows1_6"/></li>
<li><img src="Slider_images/8.jpg" alt="lucknow-accommodation" title="lucknow-accommodation" id="wows1_7"/></li>
<li><img src="Slider_images/9.jpg" alt="lucknow-cuisine" title="lucknow-cuisine" id="wows1_8"/></li>
<li><img src="Slider_images/10.jpg" alt="lucknow-flights" title="lucknow-flights" id="wows1_9"/></li>
<li><img src="Slider_images/11.jpg" alt="lucknow-local-transport" title="lucknow-local-transport" id="wows1_10"/></li>
<li><img src="Slider_images/12.jpg" alt="lucknow" title="lucknow" id="wows1_11"/></li>
<li><img src="Slider_images/13.jpg" alt="people" title="people" id="wows1_12"/></li>
<li><img src="Slider_images/14.jpg" alt="photo_1" title="photo_1" id="wows1_13"/></li>
<li><img src="Slider_images/15.jpg" alt="photo_2" title="photo_2" id="wows1_14"/></li>
<li><img src="Slider_images/16.jpg" alt="rumi-darwaza-lucknow" title="rumi-darwaza-lucknow" id="wows1_15"/></li>
</ul>
</div>


<div class="ws_bullets"><div>
<a href="#" title="05"><img src="data1/tooltips/05.jpg" alt="05"/>1</a>
<a href="#" title="bara-imambara-lucknow"><img src="data1/tooltips/baraimambaralucknow.jpg" alt="bara-imambara-lucknow"/>2</a>
<a href="#" title="front"><img src="data1/tooltips/front.jpg" alt="front"/>3</a>
<a href="#" title="image1"><img src="data1/tooltips/image1.jpg" alt="image1"/>4</a>
<a href="#" title="jama-masjid-lucknow"><img src="data1/tooltips/jamamasjidlucknow.jpg" alt="jama-masjid-lucknow"/>5</a>
<a href="#" title="l1"><img src="data1/tooltips/l1.jpg" alt="l1"/>6</a>
<a href="#" title="lko1"><img src="data1/tooltips/lko1.jpg" alt="lko1"/>7</a>
<a href="#" title="lucknow-accommodation"><img src="data1/tooltips/lucknowaccommodation.jpg" alt="lucknow-accommodation"/>8</a>
<a href="#" title="lucknow-cuisine"><img src="data1/tooltips/lucknowcuisine.jpg" alt="lucknow-cuisine"/>9</a>
<a href="#" title="lucknow-flights"><img src="data1/tooltips/lucknowflights.jpg" alt="lucknow-flights"/>10</a>
<a href="#" title="lucknow-local-transport"><img src="data1/tooltips/lucknowlocaltransport.jpg" alt="lucknow-local-transport"/>11</a>
<a href="#" title="lucknow"><img src="data1/tooltips/lucknow.jpg" alt="lucknow"/>12</a>
<a href="#" title="people"><img src="data1/tooltips/people.jpg" alt="people"/>13</a>
<a href="#" title="photo_1"><img src="data1/tooltips/photo_1.jpg" alt="photo_1"/>14</a>
<a href="#" title="photo_2"><img src="data1/tooltips/photo_2.jpg" alt="photo_2"/>15</a>
<a href="#" title="rumi-darwaza-lucknow"><img src="data1/tooltips/rumidarwazalucknow.jpg" alt="rumi-darwaza-lucknow"/>16</a>
</div></div>
<span class="wsl"><a href="http://wowslider.com">jQuery Photo Gallery</a> by WOWSlider.com v4.1</span>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="Slider_Data/wowslider.js"></script>
	<script type="text/javascript" src="Slider_Data/script.js"></script>
	<!-- End WOWSlider.com BODY section -->

    </div>
    </form>
</body>
</html>
