<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100px;
            border: 4px solid #800080;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <table align="center" cellpadding="4" cellspacing="5" class="auto-style1">
            <tr>
                <td>id</td>
                <td>
                    <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>name</td>
                <td>
                    <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>city</td>
                <td>
                    <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>select image&nbsp;</td>
                <td>
                    <asp:FileUpload ID="FileUpload1" runat="server" />
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Insert data" />
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1" OnRowDeleting="GridView1_RowDeleting" OnRowUpdating="GridView1_RowUpdating">
                        <Columns>
                            <asp:BoundField  ReadOnly="true" DataField="id" HeaderText="id" SortExpression="id" />
                            <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                            <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
                            <asp:TemplateField HeaderText="imagepath" SortExpression="imagepath">
                                <EditItemTemplate>
                                    <asp:Image ID="Image1" runat="server" Height="66px" ImageUrl='<%# Eval("imagepath") %>' Width="101px" />
                                    <asp:FileUpload ID="FileUpload2" runat="server" />
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Image ID="Image1" runat="server" Height="66px" ImageUrl='<%# Eval("imagepath") %>' Width="101px" />
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:empInfoConnectionString %>" InsertCommand="insert into login1 values(@id,@name,@city,@imagepath)" SelectCommand="SELECT * FROM [login1]" DeleteCommand="delete from login1 where id=@id" UpdateCommand="update login1 set name=@name,city=@city,imagepath=@imagepath where id=@id">
                        <InsertParameters>
                            <asp:ControlParameter ControlID="TextBox1" Name="id" PropertyName="Text" />
                            <asp:ControlParameter ControlID="TextBox2" Name="name" PropertyName="Text" />
                            <asp:ControlParameter ControlID="TextBox3" Name="city" PropertyName="Text" />
                            <asp:Parameter Name="imagepath" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="imagepath" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                </td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
