<%@ Page Language="C#" AutoEventWireup="true" CodeFile="gridviewform.aspx.cs" Inherits="gridviewform" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>gridview</title>
    </head>
<body><br />
    <center><font face="buxton sketch" size="12">GridView-Working with Table having no Primary Key 
        <br />(we cann't auto generate where clause condition)</font></center>
    <br />
    <form id="form1" runat="server">
    <div style="height: 415px">
    
       
         <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" Height="189px" Width="632px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BorderColor="Black" BorderStyle="Dotted" CellPadding="1" CellSpacing="2" DataKeyNames="id" ShowFooter="True"   >
            <Columns>
                 
                <asp:TemplateField>
                    <FooterTemplate>
                        <asp:Button ID="insert" runat="server" CommandName="insertaf" Text="Insert" OnClick="insert_Click1" />
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="id">
                    <FooterTemplate>
                        <asp:TextBox ID="idbox" runat="server"></asp:TextBox>
                    </FooterTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("id") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Name">
                    <FooterTemplate>
                        <asp:TextBox ID="namebox" runat="server"></asp:TextBox>
                    </FooterTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Eval("Name") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="city">
                    <FooterTemplate>
                        <asp:TextBox ID="citybox" runat="server"></asp:TextBox>
                    </FooterTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Eval("City") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                 
            </Columns>
                    
             
        </asp:GridView>
                    
              
                     <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                         ConnectionString="<%$ ConnectionStrings:aspdbConnectionString %>" 
                         SelectCommand="SELECT * FROM [details]" 
                         DeleteCommand="DELETE from details where id=@id" 
                         UpdateCommand="UPDATE details SET Name =@name, City =@city where id=@id" InsertCommand="INSERT INTO details(id, Name, City) VALUES (@id,@Name,@City)">
                         <DeleteParameters>
                             <asp:Parameter Name="id" />
                         </DeleteParameters>
                         <InsertParameters>
                             <asp:Parameter Name="id" />
                             <asp:Parameter Name="Name" />
                             <asp:Parameter Name="City" />
                         </InsertParameters>
                         <UpdateParameters>
                             <asp:Parameter Name="name" />
                             <asp:Parameter Name="city" />
                             <asp:Parameter Name="id" />
                         </UpdateParameters>
                     </asp:SqlDataSource>
                  
    </div>
    </form>
</body>
</html>
