<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
    </div>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id" DataSourceID="SqlDataSource1">
            <Columns>
                <asp:BoundField DataField="id" HeaderText="Emp id" SortExpression="id" ReadOnly="true" />
                <asp:BoundField DataField="name" HeaderText="Emp name" SortExpression="name" />
                <asp:BoundField DataField="password" HeaderText="Emp password" SortExpression="password" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:empInfoConnectionString %>" DeleteCommand="delete from login where id=@id" SelectCommand="SELECT * FROM [login]" UpdateCommand="update login set name=@name,password=@password where id=@id"></asp:SqlDataSource>
    </form>
</body>
</html>
